version: 0.2
phases:
  build:
    commands:
      - aws cloudformation deploy
        --capabilities CAPABILITY_NAMED_IAM
        --template-file alb-ec2-codedeploy/deploy/infra.yml
        --stack-name ${PROJECT_DEPLOYMENT_NAME}-deploy
        --parameter-overrides 
            ProjectName=${PROJECT_NAME}
            DeploymentName=${DEPLOYMENT_NAME}
            ProjectVersion=${CODEBUILD_RESOLVED_SOURCE_VERSION}
  post_build:
    commands:
      - aws deploy create-deployment
        --application-name ${PROJECT_DEPLOYMENT_NAME}
        --deployment-group-name ${PROJECT_DEPLOYMENT_NAME}
        --s3-location bucket=${PROJECT_DEPLOYMENT_NAME},key=latest/revision.zip,bundleType=zip