def gitHubProjectName='aws-dev-spring-boot-jar'
def gitCommitSha=env.GIT_COMMIT

pipeline {
        agent any
        stages{
            stage('Deploy in CodeBuild') {
                steps {
                    sh """
                        aws cloudformation deploy \
                            --capabilities CAPABILITY_NAMED_IAM \
                            --template-file ./infra/infra.yaml \
                            --stack-name ${gitHubProjectName} \
                            --parameter-overrides \
                                ProjectName=${PROJECT_NAME} \
                                ProjectVersion=${CODEBUILD_RESOLVED_SOURCE_VERSION}
                    """   
                }
            }
        }
    }