def gitHubProjectName='aws-dev-spring-boot-jar'

pipeline {
    agent any
    stages{
        stage('Deploy infrastructure') {
            steps {
                sh """
                    aws cloudformation deploy \
                        --capabilities CAPABILITY_NAMED_IAM \
                        --template-file ./infra/infra.yaml \
                        --stack-name ${gitHubProjectName} \
                        --parameter-overrides \
                            ProjectName=${gitHubProjectName} \
                            ProjectVersion=${env.GIT_COMMIT}
                """
            }
        }
    }
}