version: 0.2
phases:
  build:
    commands:
      - aws cloudformation deploy
        --capabilities CAPABILITY_NAMED_IAM
        --template-file ${DEPLOYMENT_NAME}/deploy/infra.yml
        --stack-name ${PROJECT_DEPLOYMENT_NAME}-deploy
        --parameter-overrides 
            ProjectDeploymentName=${PROJECT_DEPLOYMENT_NAME}
            ProjectVersion=${CODEBUILD_RESOLVED_SOURCE_VERSION}
            ResourceEndpoint=api
  post_build:
    commands:
      - export FUNCTION_ALIAS=alias
      - export TARGET_FUNCTION_VERSION=$(aws lambda publish-version
                              --function-name ${PROJECT_DEPLOYMENT_NAME}
                              --query "Version")
          && aws lambda create-alias
                  --function-name ${PROJECT_DEPLOYMENT_NAME}
                  --name ${FUNCTION_ALIAS}
                  --function-version ${TARGET_FUNCTION_VERSION}
          || true
      - export CURRENT_FUNCTION_VERSION=$((${TARGET_FUNCTION_VERSION}-1))
      - envsubst < ${DEPLOYMENT_NAME}/deploy/appspec.yml > appspec.yml
      - aws s3 cp appspec.yml s3://${PROJECT_DEPLOYMENT_NAME}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/appspec.yml
      - aws s3 cp appspec.yml s3://${PROJECT_DEPLOYMENT_NAME}/latest/appspec.yml