AWSTemplateFormatVersion: 2010-09-09
Description: A Java SpringBoot application (jar) deployed with Elastic Beanstalk
Parameters:
  ProjectDeploymentName:
    Type: String
  ProjectVersion:
    Type: String

Resources:

  SpringBootApplication:
    Properties:
      ApplicationName: !Ref ProjectDeploymentName
      Description: Spring boot and elastic beanstalk
    Type: AWS::ElasticBeanstalk::Application

  SpringBootApplicationVersion:
    Properties:
      ApplicationName: !Ref SpringBootApplication
      SourceBundle:
        S3Bucket: !Ref ProjectDeploymentName
        S3Key: !Sub '${ProjectVersion}/Dockerrun.aws.json'
    Type: AWS::ElasticBeanstalk::ApplicationVersion

  SpringBootBeanStalkConfigurationTemplate:
    Properties:
      ApplicationName: !Ref SpringBootApplication
      Description: A template for spring boot application deployment with DockerFile
      OptionSettings:
        - Namespace: aws:ec2:instances
          OptionName: InstanceTypes
          Value: t2.medium
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: 2
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: 4
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref BackendInstanceProfile
      SolutionStackName: 64bit Amazon Linux 2 v3.4.16 running Docker
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate

  SpringBootBeanstalkEnvironment:
    Properties:
      ApplicationName: !Ref SpringBootApplication
      EnvironmentName: !Ref SpringBootApplication
      TemplateName: !Ref SpringBootBeanStalkConfigurationTemplate
      VersionLabel: !Ref SpringBootApplicationVersion
    Type: AWS::ElasticBeanstalk::Environment

  BackendInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProjectDeploymentName}-instance-profile'
      Path: /
      Roles:
        - aws-elasticbeanstalk-ec2-role